package org.openecomp.dcae.restapi.model.ves.syslog;

public enum EVEL_SYSLOG_FACILITIES{
		  EVEL_SYSLOG_FACILITY_KERNEL,
		  EVEL_SYSLOG_FACILITY_USER,
		  EVEL_SYSLOG_FACILITY_MAIL,
		  EVEL_SYSLOG_FACILITY_SYSTEM_DAEMON,
		  EVEL_SYSLOG_FACILITY_SECURITY_AUTH,
		  EVEL_SYSLOG_FACILITY_INTERNAL,
		  EVEL_SYSLOG_FACILITY_LINE_PRINTER,
		  EVEL_SYSLOG_FACILITY_NETWORK_NEWS,
		  EVEL_SYSLOG_FACILITY_UUCP,
		  EVEL_SYSLOG_FACILITY_CLOCK_DAEMON,
		  EVEL_SYSLOG_FACILITY_SECURITY_AUTH2,
		  EVEL_SYSLOG_FACILITY_FTP_DAEMON,
		  EVEL_SYSLOG_FACILITY_NTP,
		  EVEL_SYSLOG_FACILITY_LOG_AUDIT,
		  EVEL_SYSLOG_FACILITY_LOG_ALERT,
		  EVEL_SYSLOG_FACILITY_CLOCK_DAEMON2,
		  EVEL_SYSLOG_FACILITY_LOCAL0,
		  EVEL_SYSLOG_FACILITY_LOCAL1,
		  EVEL_SYSLOG_FACILITY_LOCAL2,
		  EVEL_SYSLOG_FACILITY_LOCAL3,
		  EVEL_SYSLOG_FACILITY_LOCAL4,
		  EVEL_SYSLOG_FACILITY_LOCAL5,
		  EVEL_SYSLOG_FACILITY_LOCAL6,
		  EVEL_SYSLOG_FACILITY_LOCAL7,
		  EVEL_MAX_SYSLOG_FACILITIES
}

